//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultoría_Legal
{


    public partial class GestionDocumentos
    {

        protected global::System.Web.UI.WebControls.Label LabelBienvenida;

        protected global::System.Web.UI.WebControls.Label LabelMensaje;

        protected global::System.Web.UI.WebControls.Label LabelUsuarioSession;

        protected global::System.Web.UI.WebControls.Label LabelClaveCookie;

        protected global::System.Web.UI.WebControls.Label LabelSeleccion;

        protected global::System.Web.UI.WebControls.FileUpload FileUploadDocumento;

        protected global::System.Web.UI.WebControls.Button ButtonSubirDocumento;

        protected global::System.Web.UI.WebControls.Label LabelNombreArchivo;

        protected global::System.Web.UI.WebControls.Label LabelTamanoArchivo;

        protected global::System.Web.UI.WebControls.Label LabelTipoArchivo;
    }
}
