//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultoría_Legal
{


    public partial class Registro
    {

        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummaryRegistro;

        protected global::System.Web.UI.WebControls.Label LabelCorreo;

        protected global::System.Web.UI.WebControls.TextBox txtCorreo;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredCorreo;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularCorreo;

        protected global::System.Web.UI.WebControls.Label LabelUsuario;

        protected global::System.Web.UI.WebControls.TextBox txtUsuario;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredUsuario;

        protected global::System.Web.UI.WebControls.Label LabelEdad;

        protected global::System.Web.UI.WebControls.TextBox txtEdad;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredEdad;

        protected global::System.Web.UI.WebControls.RangeValidator RangeEdad;

        protected global::System.Web.UI.WebControls.Label LabelClave;

        protected global::System.Web.UI.WebControls.TextBox txtClave;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredClave;

        protected global::System.Web.UI.WebControls.Label LabelConfirmarClave;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmarClave;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredConfirmarClave;

        protected global::System.Web.UI.WebControls.CompareValidator CompareClaves;

        protected global::System.Web.UI.WebControls.Label LabelNombreApellido;

        protected global::System.Web.UI.WebControls.TextBox txtNombreApellido;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredNombreApellido;

        protected global::System.Web.UI.WebControls.Button ButtonRegistrar;

        protected global::System.Web.UI.WebControls.Label LabelMensaje;
    }
}
