//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultoría_Legal
{


    public partial class SiteMaster
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm formPrincipal;

        protected global::System.Web.UI.WebControls.Image ImageLogo;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
